version: '3'

services:
  zpi-pg:
    image: bitnami/postgresql
    container_name: zpi-pg
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=zpi_db
  zpi-redis:
    image: redis:alpine
    container_name: zpi-redis
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=docker
  zpi-mongo:
    image: mongo
    container_name: zpi-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: docker
      MONGO_INITDB_ROOT_PASSWORD: docker
    ports:
      - "27017:27017"