openapi: 3.0.3
info: 
  title: NotiWay - Whatsapp Notifications Sender - API REST
  description: |-
    NotiWay é uma API Rest eficiente e fácil de usar para envio de notificações via WhatsApp, voltada tanto para pequenas e médias empresas quanto para desenvolvedores de aplicações. Com a nossa API, você pode enviar mensagens personalizadas, promocionais ou informativas diretamente para os clientes, mantendo uma comunicação direta e eficaz.

    A API é baseada no modelo SaaS (Software as a Service) e pode ser integrada facilmente com outras aplicações e serviços, proporcionando mais eficiência e praticidade para a sua empresa.

    Nossa equipe está sempre à disposição para ajudar em qualquer dúvida ou problema que possa surgir, garantindo uma experiência de uso excepcional para nossos clientes. Se você está procurando uma solução moderna e eficiente para envio de notificações via WhatsApp, a API da NotiWay é a escolha perfeita!
  termsOfService: http://swagger.io/terms/
  contact:
    email: suporte@notiway.com.br
  version: 1.0.0
servers:
  - url: https://api.notiway.com.br/messages
paths:
  /send-text:
    post:
      tags:
        - messages
      summary: Enviar mensagem de texto
      description: Está rota é responsavel por enviar uma mensagem texto para o contato indicado.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                to:
                  type: string
                  example: 5511999999999
                message:
                  type: string
                  example: Esta mensagem será enviada ao contato
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: sended
        '400':
          description: teste de erro
       