openapi: 3.0.3
info: 
  title: NotiWay - Whatsapp Notifications Sender - API REST
  description: |-
    NotiWay é uma API Rest eficiente e fácil de usar para envio de notificações via WhatsApp, voltada tanto para pequenas e médias empresas quanto para desenvolvedores de aplicações. Com a nossa API, você pode enviar mensagens personalizadas, promocionais ou informativas diretamente para os clientes, mantendo uma comunicação direta e eficaz.

    A API é baseada no modelo SaaS (Software as a Service) e pode ser integrada facilmente com outras aplicações e serviços, proporcionando mais eficiência e praticidade para a sua empresa.

    Nossa equipe está sempre à disposição para ajudar em qualquer dúvida ou problema que possa surgir, garantindo uma experiência de uso excepcional para nossos clientes. Se você está procurando uma solução moderna e eficiente para envio de notificações via WhatsApp, a API da NotiWay é a escolha perfeita!
  termsOfService: http://swagger.io/terms/
  contact:
    email: suporte@notiway.com.br
  version: 1.0.0
servers:
  - url: https://api.notiway.com.br/messages
paths:
  /send-text:
    post:
      tags:
        - messages
      summary: Enviar mensagem de texto
      description: Está rota é responsavel por enviar uma mensagem texto para o contato indicado.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#components/schemas/textMessage'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#components/responses/successResponse'
        '400':
          $ref: '#components/responses/ValidationError'
        '401':
          $ref: '#components/responses/UnauthorizedError'
        '425':
          $ref: '#components/responses/NotReadyError'
        '5xx':
          $ref: '#components/responses/ServerError'
  /send-link:
    post:
      tags:
        - messages
      summary: Enviar mensagem com link
      description: Está rota é responsavel por enviar uma mensagem contento texto e um link com o preview do mesmo.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#components/schemas/linkMessage'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#components/responses/successResponse'
        '400':
          $ref: '#components/responses/ValidationError'
        '401':
          $ref: '#components/responses/UnauthorizedError'
        '425':
          $ref: '#components/responses/NotReadyError'
        '5xx':
          $ref: '#components/responses/ServerError'
  /send-location:
    post:
      tags:
        - messages
      summary: Enviar localização
      description: Está rota é responsavel por enviar uma localização ao contato.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#components/schemas/locationMessage'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#components/responses/successResponse'
        '400':
          $ref: '#components/responses/ValidationError'
        '401':
          $ref: '#components/responses/UnauthorizedError'
        '425':
          $ref: '#components/responses/NotReadyError'
        '5xx':
          $ref: '#components/responses/ServerError'
  /send-contact:
    post:
      tags:
        - messages
      summary: Enviar um contato
      description: Está rota é responsavel por enviar um contato.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#components/schemas/contactMessage'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#components/responses/successResponse'
        '400':
          $ref: '#components/responses/ValidationError'
        '401':
          $ref: '#components/responses/UnauthorizedError'
        '425':
          $ref: '#components/responses/NotReadyError'
        '5xx':
          $ref: '#components/responses/ServerError'
  /send-gif:
    post:
      tags:
        - messages
      summary: Enviar um gif
      description: Está rota é responsavel por enviar um gif ao contato.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#components/schemas/gifMessage'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#components/responses/successResponse'
        '400':
          $ref: '#components/responses/ValidationError'
        '401':
          $ref: '#components/responses/UnauthorizedError'
        '425':
          $ref: '#components/responses/NotReadyError'
        '5xx':
          $ref: '#components/responses/ServerError'
  /send-sticker:
    post:
      tags:
        - messages
      summary: Enviar um sticker
      description: Está rota é responsavel por enviar um sticker ao contato.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#components/schemas/stickerMessage'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#components/responses/successResponse'
        '400':
          $ref: '#components/responses/ValidationError'
        '401':
          $ref: '#components/responses/UnauthorizedError'
        '425':
          $ref: '#components/responses/NotReadyError'
        '5xx':
          $ref: '#components/responses/ServerError'
components:
  schemas:
    textMessage:
      required:
        - to
        - message
      type: object
      properties:
        to:
          type: string
          example: 5511999999999
        message:
          type: string
          example: Esta mensagem será enviada ao contato
    linkMessage:
      required:
        - to
        - url
      type: object
      properties:
        to:
          type: string
          example: 5511999999999
        url:
          type: string
          example: http://www.google.com.br
        message:
          type: string
          example: Esta mensagem será enviada ao contato
    locationMessage:
      required:
        - to
      type: object
      properties:
        to:
          type: string
          example: 5511999999999
        latitude:
          type: number
          example: -23.561414
        longitude:
          type: number
          example: -46.6558819
        title:
          type: string
          example: MASP - Museu de Artes de São Paulo
        address:
          type: string
          example: Av. Paulista, 1578 - Bela Vista, São Paulo - SP, 01310-200
    contactMessage:
      required:
        - to
        - name
        - contact
      type: object
      properties:
        to:
          type: string
          example: 5511999999999
        name:
          type: string
          example: John Doe
        contact:
          type: string
          example: 5511988888888
    gifMessage:
      required:
        - to
        - url
      type: object
      properties:
        to:
          type: string
          example: 5511999999999
        url:
          type: string
          example: https://media.giphy.com/media/hpXFi66bfQm7e81ohw/giphy.gif
    stickerMessage:
      required:
        - to
        - url
      type: object
      properties:
        to:
          type: string
          example: 5511999999999
        url:
          type: string
          example: https://www.camarabracodotrombudo.sc.gov.br/media/noticia/link-para-participacao-da-audiencia-publica-54.jpg
  responses:
    successResponse:
        type: object
        properties:
          status:
            type: string
            example: sended
    UnauthorizedError:
      description: Unauthorized.
    NotReadyError:
      description: Client or sender not ready.
    ValidationError:
      description: Validation error.
    ServerError:
      description: Unexpected error.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
